# Generated by Django 3.2.5 on 2021-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premier',
            options={'ordering': ('-id',)},
        ),
        migrations.AddIndex(
            model_name='premier',
            index=models.Index(fields=['premier_at'], name='premiers_premier_da73dd_idx'),
        ),
    ]
