# Generated by Django 3.2.5 on 2021-07-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deactivated',
        ),
    ]
